title: Anusree P. Sunilkumar

logo: /assets/images/anu.jpg

description: >
  Vision AI Engineer | AI Researcher
  specializing in Computer Vision,
  Medical Imaging, and 3D Reconstruction.

show_downloads: false

theme: jekyll-theme-minimal
